### ISSUE TITLE
Possible black-on-black on "did you know" dialog.

### ISSUE THREAD

**Issue by falkTX** [muse-sequencer/muse#359] opened 2015-01-28 23:33 UTC
Me having a black/dark theme means windows backgrounds are black.
muse is forcing black text on the dialog, ending up with black-on-black.

It looks like this:
![scr426](https://cloud.githubusercontent.com/assets/1334853/5949474/f00eabfa-a745-11e4-8da7-73054f7d5dcc.png)

Text is unreadable.

PS: There is probably other black-on-black issues in muse, please never force the text color.
Or if you do, set the background to white.

**Comment by spamatica** [comment] 2015-01-29 08:23
Hi falkTX,

oh man that's no good. Though, I have to ask you a bit about what style, windowmanager, distribution etc you are using?
I implemented this and I have to admit I sometimes do stupid decisions. ;) but I can't reproduce this and forcing the text color in a standard dialog seems silly even by my standards..

Thanks for all your hard work with kxstudio by the way, awesome work!

**Comment by falkTX** [comment] 2015-01-29 17:18
If you set your theme as a dark/black one I'm sure you'll experience this.
(Anything that has a very dark window background)

Here's muse with oxygen + zion-reversed colors:
![scr026](https://cloud.githubusercontent.com/assets/1334853/5962285/bff16b52-a7da-11e4-9c72-bdebb8fb74da.png)

The issue is clearly that the text inside the dialog is forced black.
I'm guessing due to some html/css styling.

**Comment by spamatica** [comment] 2015-01-29 21:26
Oh, the danger of assumptions. I was so sure you had set the style inside muse, then it works. Learned something new in the process, I've never even tried playing with the default colors before ;)

Indeed there was a problem, somehow the ui file had a hardcoded palette, can't imagine how that could have happened but it was there. Fixed now.
Thanks!

**Closed by spamatica** 2015-01-29 21:26 UTC
