### ISSUE TITLE
graphic master track loses KB shortcut [sf#1650979]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#198] opened 2013-09-10 15:15 UTC
Submitted by songshop on 2007-02-02 22:53:00

when scrolling back and forth you lose you keyboard shortcuts( >>, <<, play, etc) change focus to main window and back returns the functionality to GMT.

**Comment by spamatica** [comment] 2019-11-22 23:21
Cannot reproduce so closing. The bug is very old, could have been due to some qt version.

**Closed by spamatica** 2019-11-22 23:21 UTC
Labels: bug, import, midi
