### ISSUE TITLE
Make it harder to inadvertently add or remove tracks

### ISSUE THREAD

**Issue by bluebear94** [muse-sequencer/muse#871] opened 2020-10-15 04:24 UTC
Right-clicking the track pane (or an existing track there) for too long tends to inadvertently add or remove tracks. I think this happens because right-click menus don't require a separate click to confirm an option; this should be changed, at least as a user setting. (I couldn't find such a setting.)

**Comment by kybos** [comment] 2020-10-15 09:30
I don't understand.
I right-click to open the context menu. Then I can move the mouse over the item I want to trigger and then I have to click a mouse button again to confirm, otherwise nothing will happen.

**Comment by bluebear94** [comment] 2020-10-15 13:08
It might actually be my OS that's responsible for this behavior. For some reason, accidentally triggering the right-click menu seems to happen more often in MusE for me, though.

**Comment by terminator356** [comment] 2020-10-15 14:50
Hello. Just a wild guess here:
Mouse buttons can become dirty, and cause no triggering or false triggering.
In this case of holding the mouse button down while opening a right-click menu,
 dirty mouse buttons could be a problem, causing the computer to think that the button was released.
Tim.

**Comment by kybos** [comment] 2020-10-29 09:38
You were right, it happened to me too now!
The problem is that the menu item can also be triggered by the right mouse button, which is used to call up the context menu. So if you still hold the RMB and move the mouse just a little, then the first menu item is easily triggered.
Will be fixed, it's obvious that especially in context menus the items must be triggered by left mouse button only.

**Comment by kybos** [comment] 2020-10-29 15:08
I checked the Qt docu, there is no attribute to disable the right or middle buttons for menus. It is so "by design" and it's consistent for all menus, so I think it's no good idea to mess up with it.
Strange thing is that now I can't reproduce the behaviour described above (moving mouse + releasing triggers item). So probably my mouse is dirty too, as Tim suggested...

**Closed by kybos** 2020-10-29 15:08 UTC
