### ISSUE TITLE
Naming a track with acentuated letter

### ISSUE THREAD

**Issue by moebius1** [muse-sequencer/muse#645] opened 2019-03-24 10:22 UTC
Bonjour,

I think it's a regression but I'm not sure ;
Anyway, when I name a track  «Ténor» for example (without quotes :-) ) and then save the whole song, when reloading the same song the track name appears like «T<2 squares>nor». I've tried to put a picture of the result name here.
It seems that utf8 encoding doesn't work for naming tracks.

cordialement,
[
![sample](https://user-images.githubusercontent.com/1695176/54878041-eb9a6a00-4e26-11e9-9acb-d391a90837b3.png)
](url)

**Comment by terminator356** [comment] 2019-03-24 18:17
Observed! Yes, it's a regression. Caused by me a few months ago in my "Xml makeover".
Crud! That's what I get for removing the QByteArray stuff in our Xml code.
I may be too late here, but please DO NOT **save** the file(s), the characters will be messed up !

Mt apologies. Please wait... Fixing, somehow...

**Comment by moebius1** [comment] 2019-03-24 19:31
Thank you for your fast answer and don't worry : I've changed everything 
from «Ténor» to «Tenor», including corresponding audio-track. I think 
I've already changed names in some other(s) older piece(s). It's not too 
important and I'll be waiting for fixes before looking at these old 
pieces (I use Muse since a long time now ! ).

cordialement,

**Comment by terminator356** [comment] 2019-03-25 18:29
Fixed in git master now. From ChangeLog:
`
      - Fix issue 645 "Naming a track with acentuated letter".
        Oops, regression from 07.01.2019: utf8 chars were corrupted.
        Reverted by re-adding QByteArray stuff, required for proper parsing.
      - Also fixed many double &amp; in *.idf files and a few other things.
      - Fixed bug in storing sysex comment xml section of midi instruments.
        It was doing escape replacements twice, corrupting the text.

`
Try it out...
Thank you for catching this. A disaster waiting to happen, if released into the wild.

**Comment by spamatica** [comment] 2019-11-22 23:45
Seems to be fixed. Closing, Reopen if it is still a problem.

**Closed by spamatica** 2019-11-22 23:45 UTC
