### ISSUE TITLE
Sent Midi notes are off by one semitone

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#1104] opened 2022-11-11 16:06 UTC
**Describe the bug**
When _playing_ a Midi track, all notes are one semitone too high. When I _click_ on the event in the _pianoroll_ editor, the pitch is correct.

**To reproduce**
- Create a Midi Track and connect it to a synth
- Create a Part in that Track and edit the Part in the Pianoroll editor
- Add a note (say a C) with the pencil. You'll hear a C
- Play the part. You'll hear a C#

**What else I tried**
I connected MusE to _GMIDImonitor_ to look at the events and indeed, what should be a _C_ came out as a _C#_. 

I didn't notice anything strange with drum tracks.

**Comment by donarturo11** [comment] 2022-11-15 09:34
So. I tested on my machine and few configurations: synth in my card (DreamBlaster daughterboard), QSynth and builtin MusE plugin - FluidSynth I added a note C and heard C. I played part and heard C too. Could you send your file or video, please?

**Comment by spamatica** [comment] 2022-11-15 11:55
My first guess would be that the transpose property for the midi track is not at zero?
If it does really occur on newly created midi tracks that is very curious...

**Comment by donarturo11** [comment] 2022-11-15 14:00
@spamatica I checked this case. I set transposition to 1 and clicked and played, in both cases sound in synth is in correct pitch: eg. C in 0 always played as C and with one as C sharp. Another case is not possible.
I can yet check if always click or play C (in MIDI number 60), midi monitor will return 60, but after my tests I'm totally sure, that MIDI tracks run correctly.

**Comment by donarturo11** [comment] 2022-11-15 14:03
@drautzburg Could you send us your .med file, eventually video, please? It would be very helpful.

**Comment by terminator356** [comment] 2022-11-15 15:38
> My first guess would be that the transpose property for the midi track is not at zero? If it does really occur on newly created midi tracks that is very curious...

Yes that seems to be the only avenue that this could occur.
(The transpose property is available on the midi mixer strip 'Prop' tab.)
I know of no other code that would add or subtract values from the note.
Well, actually there is the midi 'transformator' window which could also do it.
If there was some leftover setting in there and forgot it was on...

**Comment by drautzburg** [comment] 2022-11-15 18:04
I tried to make a short example, and the first time I tried the notes surprisingly (to me) came out okay. Clicking on the event and playing the track produced the same pitch. Then I did "something" the the off-by-one error occurred. I cannot send you the .med file ("unsupported") and the video (too big) via github, so I put it on my google drive:

https://drive.google.com/drive/folders/1A0FU2pWonp7Q8aJmtvCd9PDNo51fWyU2?usp=sharing

**Comment by drautzburg** [comment] 2022-11-16 11:01
Apparently I had not granted access to the drive folder. Sorry for that. Should work now. 
Also sorry, video came out quite blurry. It was my first time screen-capturing.

**Comment by spamatica** [comment] 2022-11-16 22:04
Somewhat to my astonishment I could reproduce the issue!
It turns out the song file had a property globalPitchShift="1" set.
It looks like this comes from one of the toolbars where there is a Pitch setting for midi. Set it to zero and all should be well.

I've been around MusE for well over 20 years and thought I knew about most features, but this one was new to me ;)
I'm closing the bug. In case this isn't so straight forward let us know.

**Comment by spamatica** [comment] 2024-04-26 15:50
This should finally be fixed in master now.

**Closed by spamatica** 2024-04-26 15:50 UTC
