### ISSUE TITLE
Step record missing C1 note

### ISSUE THREAD

**Issue by emillo** [muse-sequencer/muse#639] opened 2019-02-12 09:17 UTC
Hello, 
I'm running the last master branch on debian stretch, and the step recording has a strange behaviour: the note C1 is never been recorded, even if the cursor is advanced. All other notes work.

Regards
Emiliano

**Comment by emillo** [comment] 2019-02-12 11:35
I found out that the note C1 is used as "insert pause" in midi->input plugins->midi remote control , however is not active (or at least Activate-> on is not selected), by changing it to other note it works.

**Comment by terminator356** [comment] 2019-02-19 17:18
Hello, I have re-arranged the 'midi remote control' dialog box to make things more clear.
(That is, clear that the 'insert pause' box is NOT (de-)activate-able.)
In git master now. Sorry for any confusion.

**Comment by spamatica** [comment] 2019-11-23 17:04
Closing this as it seems to be by design then (and hopefully clearer in the UI)

**Closed by spamatica** 2019-11-23 17:04 UTC
