### ISSUE TITLE
Soft synth track add - inconsistent behaviour

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#668] opened 2019-10-31 17:22 UTC
Hi,
When adding a soft synth track, most synths are inserted quietly, with two exceptions: MESS vam and MESS organ, which both open the GUI. Is that intended?
Cheers,
Kybos

**Comment by terminator356** [comment] 2019-11-03 23:00
Probably just an oversight.
They all used to open until someone quieted them.
I'll keep my eyes open for the cause, thanks.

**Comment by kybos** [comment] 2019-11-04 05:31
I personally would very much prefer if the (native) GUI did NOT open at inserting. Especially because some synths crash the complete application immediately. Or perhaps make it a setting?

**Comment by spamatica** [comment] 2019-11-04 22:30
Indeed it should not. I think I tried to fix this at atleast one point but couldn't figure out what was going on.. I'll have a look again

**Comment by spamatica** [comment] 2019-11-04 22:46
Fixed in master

**Closed by spamatica** 2019-11-04 22:46 UTC
