### ISSUE TITLE
How to change the color of white vertical 'table' lines in track list and midi editor?

### ISSUE THREAD

**Issue by ViktorNova** [muse-sequencer/muse#362] opened 2015-03-29 15:04 UTC
I am making a dark theme, and cannot for the life of me figure out how to change the colors of these white vertical divider lines in the track list and midi editor 
![2015-03-29-080232_1280x800_scrot](https://cloud.githubusercontent.com/assets/3234333/6886176/157ef782-d5ea-11e4-94e4-5caaba6b5fc6.png)

This shows up few other places, I'm assuming it's some kind of global setting?

**Comment by spamatica** [comment] 2015-03-30 09:52
Hello Victor, 
It's probably hard coded. I'll see what I can do to make it configurable.

**Comment by spamatica** [comment] 2015-04-03 09:28
Hello again Victor, if you are able to test with recent head do see if this solves it for you? I added configuration options for raster in midi editors and section dividers in track list.

**Comment by ViktorNova** [comment] 2015-04-03 11:38
Awesome! It works great, thanks for fixing this so quickly. This opens up whole new possibilities for theming, it's crazy how much difference that makes. 

I darkened the ones you just made configurable, and found a few more that look like they are hardcoded:
![image](https://cloud.githubusercontent.com/assets/3234333/6981457/8477e994-d9b6-11e4-9644-987bb890dbc5.png)

The ones I noticed are 
   - Track list top and bottom border
   - Horizontal lines in drum editor
   - Drum list borders
   - Drum list text
   - Bars 2,3,4 in midi/drum editor
   - Selected track highlight
   - Arranger part name

If you don't feel like doing all of these I can probably figure it out by looking at your latest commit. 
I've never gotten Muse to look so good before, this is cool!

**Comment by spamatica** [comment] 2015-04-05 10:12
Hi Victor,

Great that it worked as intended.

I can probably help with the others but it'll be a little while so I would
definitely not mind if you could get your hands dirty :) On the contrary I
encourage dipping your toes in the code.

If you produce some themes I'd be happy if we could add them to the main
repository or atleast take some cool screenshots that we can put up on the
home page :)

Regards,
Robert


2015-04-03 13:38 GMT+02:00 Viktor Nova <notifications@github.com>:

**Comment by ViktorNova** [comment] 2015-04-10 10:43
Robert,
I will dive in and take a stab at this soon, I took a look at your commit and I don't think I'll have a problem figuring it out, in which case I will definitely send a pull request. 

As for including my themes, absolutely! I'm not much of a coder, but UI is totally my thing and I'm happy to hear you are open to including new themes. I'll open a PR for my scifi/black theme once I have it complete enough to include (which will of course be after making a few more of the hard-coded colors configurable=)

**Comment by kybos** [comment] 2020-06-14 10:14
5 years gone, I think we can close this one.
Most of the things mentioned above have been made customizable in the meantime, plus many more other UI elements.

**Closed by kybos** 2020-06-14 10:14 UTC
