### ISSUE TITLE
Automation has no does nothing when playing tracks

### ISSUE THREAD

**Issue by lpgasparotto** [muse-sequencer/muse#817] opened 2020-06-08 05:51 UTC
Hi,
I'm using MusE 3.1 on Fedora 31 KDE. I'm working on a song on which I need to set different volume levels for different sections of the audio tracks. I defined and setted the events and values but the automation is ignored when playing those tracks. Automation option is "Read" ("Lectura" in Spanish) but I tested the other alternatives and got the same behavior
![Muse-Automation](https://user-images.githubusercontent.com/22053235/83996517-c3673000-a932-11ea-92fc-5be87c2cd2eb.png)
Am I doing something or is it a bug?
Thank you very much in advance,
Luis Pablo

**Comment by Gnlfz007** [comment] 2020-06-08 07:41
I just tried this yesterday with MusE 3.1 built from GIT, with pan an vol and it works as expected.
A little pitfall may be the selection of the automated channel. The best way to get familiar with it is the recording from the faders (write) and then making the traces visible in the track. This way you are sure you addressed the right automation parameters.
Btw; recording from the faders is next to useless because it generates so many data points which can only be modified individually with the mouse. No removing a range, no ruler function to ramp up or down a range. That's odd. I may be missing something, I'm a MusE newbie.

**Comment by spamatica** [comment] 2020-06-08 08:05
The scenario you describe should absolutely work. The option Read/Lectura is fine (just as long as it is not set to Off).
If you select one of the tracks with automation and set the play position before and after the change, does the volume slider in the channel strip not change?
.. I see these are stereo tracks, I very seldom record in stereo. Maybe there is some issue there...

"Btw; recording from the faders is next to useless because it generates so many data points which can only be modified individually with the mouse. No removing a range, no ruler function to ramp up or down a range. That's odd. I may be missing something, I'm a MusE newbie."
This is a good observation, we need better tools to handle manual automation.

**Comment by lpgasparotto** [comment] 2020-06-08 16:07
You're right! These are stereo tracks. The volume sliders don't move at all when move the cursor over the events positions.
I tried to define the automation events by using the mouse and by creating events from the volume slider contextual menu (Add event > move the slider to de desired value > Set event).
I'll test it with mono tracks.

**Comment by lpgasparotto** [comment] 2020-06-08 20:26
I tested automation with a mono track and automation didn't work.
![Muse-Automation-2](https://user-images.githubusercontent.com/22053235/84076833-d880a500-a9ac-11ea-87d2-09df73de4e5c.png)
![Muse-Automation-3](https://user-images.githubusercontent.com/22053235/84076861-e2a2a380-a9ac-11ea-89d9-098fb75ecfd5.png)
Volume slider does not change beyond the automation events. What could I be doing wrong? I guess I'm doing something wrong, otherwise there must be a lot of people reporting the same issue.
Thank you very much for your replies.

**Comment by lpgasparotto** [comment] 2020-06-08 21:04
After some experimentation I found it works OK on newly started projects. I tested first with a mono track:
![Muse-Automation-4](https://user-images.githubusercontent.com/22053235/84079964-ce14da00-a9b1-11ea-96dc-530121e8e5f8.png)
![Muse-Automation-5](https://user-images.githubusercontent.com/22053235/84079977-d3722480-a9b1-11ea-9b94-09f5979d1d82.png)
After doing this I tested it with a stereo track:
![Muse-Automation-6](https://user-images.githubusercontent.com/22053235/84080020-e5ec5e00-a9b1-11ea-9730-20f86c8d07a9.png)
![Muse-Automation-7](https://user-images.githubusercontent.com/22053235/84080039-ed136c00-a9b1-11ea-9cc5-476753037fee.png)
There was something weird then, the mixer showed only one volume meter as if the clip were mono instead stereo, so I saved the file and reopened. Then the mixer showed to meters as expected, I did the automation again and it worked flawlessly:
![Muse-Automation-8](https://user-images.githubusercontent.com/22053235/84080227-38c61580-a9b2-11ea-9884-5ac93c25ae54.png)
![Muse-Automation-9](https://user-images.githubusercontent.com/22053235/84080247-3e236000-a9b2-11ea-9a7b-fc0f49cb4564.png)
I suspected the original issue could be related to the plugin I was using in the original project so I added the same plugin and it worked again:
![Muse-Automation-10](https://user-images.githubusercontent.com/22053235/84080314-627f3c80-a9b2-11ea-97dc-e21d2c51f062.png)
![Muse-Automation-11](https://user-images.githubusercontent.com/22053235/84080329-6612c380-a9b2-11ea-8f69-762609bafe66.png)
I can't find out what could be wrong in the original project which makes the automation to fails.

**Comment by lpgasparotto** [comment] 2020-06-09 17:49
Finally, I decided to make this project again from zero (the audio clips were recorded previously) and automation works OK now.

If you want I could send you both .med files if this helps to find out what was wrong with the initial project.

**Comment by spamatica** [comment] 2020-06-09 20:36
Great you got it working.
Did you start the previous song in this version of MusE also?
If you used a previous version (especially if it was between releases) there is always the possibility there was something temporarily broken, this has happened a few times.

Do attach the med files here, especially if both are done with MusE 3.1. I think that would help us.

**Comment by lpgasparotto** [comment] 2020-06-11 19:17
Great! I'm glad you found the cause. Thank you very much for your time. I did a click on that menu item just to see what happens, expecting to see an additional automation scheme or graphic but nothing happened. After seeing your screenshot I realized 2 things:
- In dark themes there's no check box, the icon works as a check reference but it's almost impossible to figure out if it's ON or OFF, this is how it looks in dark themes:
![Muse-Automation-12](https://user-images.githubusercontent.com/22053235/84429331-51c30680-abfe-11ea-9eeb-4eb5c5b2fdf0.png)
- The Spanish translations says "Mezcla de automatización" which in English means "Automation mix", the right translations should be "Automatización de Mezcla", "Automatización de consola" or "Automatización de mixer" as "mixer" is a commonly used word by the audio people. I'll check it when I work on the translation file.

**Comment by terminator356** [comment] 2020-06-11 19:57
Perhaps @kybos can comment, whether it's a style or stylesheet problem
 and how to deal with it.

I too was thinking about renaming that command.
Maybe something like "Enable all automation"
Because the word "mixer" implies that somehow it only relates to the mixer,
 but really it applies to all audio automation. So I can see it may cause confusion,
 users might not realize its importance. And we should add a popup tool-tip there, I think
 that is allowed for menu entries but maybe some styles will not show the tool-tip.

Meanwhile: I have found the cause of the **feedback** and pinned **meters**.
I am working on a solution right now. Stay tuned, hopefully will be fixed...

**Comment by kybos** [comment] 2020-06-11 20:23
The problem is that this menu item is a switch/checkbox so the handling should be left to the style (like e.g. the items in the Display menu). But in this case we override this by setting another icon over it, so most (especially) dark styles can't make the state clearly visible any more.
So just remove the icon from the action:

      autoMixerAction = new QAction(tr("Enable Automation"), this);

instead of
//      autoMixerAction = new QAction(QIcon(*MusEGui::automation_mixerIcon), tr("Mixer Automation"), this);

(in app.cpp)

should do the trick.

And please no tooltips in menus ;-). That causes just too much popping up, there is good reason it's never used, though technically possible.

**Comment by kybos** [comment] 2020-06-11 20:51
Another possibility: Try to recreate the two-column-icon-design of the KDE styles in our own (dark) styles. I checked the Qt docu and it seems possible, though not quite straight forward. 
I personally find these two icon columns a little exaggerated...

**Comment by terminator356** [comment] 2020-06-11 22:38
I noticed that some styles show a checkbox and the icon side by side,
 some styles show just the icon (as the checkbox), and some styles
 don't even show any icons at all, just a checkbox alone.

**Comment by terminator356** [comment] 2020-06-11 22:48
- Audio: Fixed bad feedback / pinned meters with muted tracks in play mode.
      Was problem near end of WaveTrack::getData(), what constitutes "have data" or not.
      Said "have data" when there was none when muted, causing AudioTrack::copyData()
       to build up feedback data in the buffers instead of clearing them.

Try it out. Lemme know if any more audio feedback trouble.
Thanks again for the test files, they really helped recreate the problem.

**Comment by lpgasparotto** [comment] 2020-06-12 04:52
Great! Thank you very much for taking care about my post. I'll download and compile the git version as soon as possible.
Best regards!

**Comment by spamatica** [comment] 2020-06-12 11:20
Yay, this is great. So it turns out we have a setting for turning on/off automation. :D Did not remember that one.
Following this discussion two steps behind... is there really a good reason to keep this as a user setting? Maybe for debugging but I wonder.. 
What do you think about removing it?

Regarding the feedback fix, this is great! I will be checking shortly!

**Comment by kybos** [comment] 2020-06-12 11:46
Removing it was my first idea too, but I dared not suggest it ;-), assuming there must be some reason why it's there (but given the wrong menu text and still worse translations, as it comes out, I can hardly imagine it was of any use...).

**Comment by terminator356** [comment] 2020-06-12 16:42
I didn't add it, I just maintain it ;-)

It could be part of the bigger solution I was planning. Recall I mentioned replacing
 the automation popup menu with my treeview (which I just re-added to the git).
However, users would have access to each automation setting (off/read/touch/write)
 at a glance all in one place and could use them to disable individual controllers.
Using a Ctrl key we could easiiy allow them to disable a whole column of controllers.
So this menu setting may be unnecessary.

I propose leaving the actual mechanism in place (places that check the setting
 and apply controllers or not) for now, but **remove the menu setting** and force
 it to be on (in case someone's song had left it off, as is the case here).
Then determine later whether to completely remove the whole thing
 or whether it is useful as a master enabler, even just for debugging.

**Comment by terminator356** [comment] 2020-06-12 22:27
Done. Gone from menu. Fixed as enabled in the code for now.

**Comment by kybos** [comment] 2020-06-13 18:55
To cope with the problem of menu checkboxes not being distinguishable on some styles:

I implemented a new option (Appearance->Styles->Show icons in menus) to hide the custom icons in menus, so only the real checkboxes are displayed.
Generally I like the look without the icons almost better, it's clean and most of the menu icons are not SVG and quite pixelated anyway with HiDPI ;-) ).

**Closed** 2020-09-10 15:10 UTC
