### ISSUE TITLE
Switching songs using guitarix crashes MusE

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#532] opened 2016-08-19 14:42 UTC
Sometimes I cannot switch Songs with File/Open or File/Open Recent. MusE crashes like this:

```
projPathPtr /
SOUNDFONT FILENAME + PATH /music/sf/GeneralUser GS 1.44 FluidSynth/GeneralUser GS FluidSynth v1.44.sf2
SOUNDFONT FILENAME + PATH /usr/share/sounds/sf2/FluidR3_GM.sf2
SOUNDFONT FILENAME + PATH /usr/share/sounds/sf2/TimGM6mb.sf2
aux index 1
found new index! 1
/home/martin/bin/myMuse: line 14: 16766 Segmentation fault      /usr/local/stow/muse3/bin/muse3 -A -J -N -I -L
```

When I pass some junk on the commandline ("lkjlkj") then I get an empty arrangement and from there I can open another song. But once that song is open I can no longer switch to yet another song.

I ran MusE in gdb and it told me the segfault happens in 

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffdcd5398f in ?? () from /usr/lib/ladspa/ladspa_guitarix.so
```

**So unless MusE has errors in unloading the plugin, this is not its fault**, but I thought I let you know. 

I can also load a song using guitarix by putting it on top of my project list, but once loaded I cannot not load it again. This even happens when I switch to a song that does **not** use guitarix. The poblem occurs when switching **away** from a guitarix song. Removing the guitarix plugin from the song (which is a pain to control anyways) seems to fix the problem.

**Comment by spamatica** [comment] 2019-11-20 18:36
There can always be unknown errors.. this one looks like guitarix though. 
Our detection of plugins has been much improved, not sure it affects this though.
Anyway, I tried this scenario and could not reproduce the crash so closing the issue for now.

**Closed by spamatica** 2019-11-20 18:36 UTC
