### ISSUE TITLE
punch problems

### ISSUE THREAD

**Issue by moebius1** [muse-sequencer/muse#649] opened 2019-05-08 18:02 UTC
Bonsoir,

Well, it's the day....
I've two problems to mention in punch 
-midi : when punching, the former sequence segment  inside locators is heard while recording the new one. Perhaps, do I make wrong action... but, if it's the normal behavior, I think it would be better to mute the former segment when recording the new one.
-audio : I can't replace a segment by a new one. When punching, even if 'replace' is selected, as in midi mode I hear the former segment I want to replace and the result is a new part inside locators that is added to the part 'below'.
 
Well, another thing (the last one ) : what is the meaning of this icon in the transport window, a red triangle with something like a jack plug in the middle ?
![image](https://user-images.githubusercontent.com/1695176/57397028-06a11d80-71cc-11e9-9447-d526cebf7285.png)

thank for all,

cordialement,

**Comment by moebius1** [comment] 2020-03-25 10:14
Bonjour,
I've searched everywhere but I still don't know how to punch correctly both audio and midi.
Well, when I was working with cubase and atari falcon, punch worked like that :
- setting left and right locator according to the place where you want to replace the record by another one then clicking on "punch in" and "punch out"
- setting the transport locator a little bit before left locator
- begin recording.
when transport locator reached the left locator, the previous record was not heard and replaced by the new one ; when reaching right locator recording stopped and turned to listen mode until you stop.
Problem in Muse : 
even I select "replace" for "record mode" in the transport window the previous record is heard and not deleted ; only a new part is created between the left and right locators and the initial part is left unchanged. The result is two parts on same track.
Well I don't know what to do to obtain a real punch action ; I surely miss something but don't know what it is...I need some help ! :-)
cordialement,

**Comment by terminator356** [comment] 2020-06-08 22:11
Update: Work is taking place in anther branch to fix at least the midi looping.
It is going well but sorry I'm running late, interrupted by all sorts of other... bugs.

**Comment by kybos** [comment] 2021-02-12 20:39
Closing this as duplicate of #789.

**Closed by kybos** 2021-02-12 20:39 UTC
