### ISSUE TITLE
MusE 3.1 fails to receive audio data on the right channel of stereo input tracks

### ISSUE THREAD

**Issue by Gnlfz007** [muse-sequencer/muse#810] opened 2020-05-21 17:17 UTC
An input track set to stereo and connected to the jack inputs (stereo too) only receives signal on the left channel, according to the level meters. A stereo recording from this input track shows signal on the left channel only. Swapping the input wiring results in signal on the left channel too (expected: right channel).

Within the same jack session, audacity records stereo in jack mode, out of the box, without any issue.

Environment: 

- MusE 3.1, built from the GIT master branch this week.
- Xubuntu 20.04 updated today (kernel 5.4.0-29-generic)
- Jack 1.9.12, pulseaudio completely uninstalled.
- Behringer XENYX302 USB

This issue may be related to #799.

**Comment by Gnlfz007** [comment] 2020-05-23 10:22
Workaround to set default of audio Input tracks to stereo:

diff --git a/muse3/muse/audiotrack.cpp b/muse3/muse/audiotrack.cpp
index ec45deab..8f923408 100644
--- a/muse3/muse/audiotrack.cpp
+++ b/muse3/muse/audiotrack.cpp
@@ -2380,8 +2380,8 @@ RouteCapabilitiesStruct AudioTrack::routeCapabilities() const
 //---------------------------------------------------------
 
 AudioInput::AudioInput()
-   // Default 1 channel for audio inputs.
-   : AudioTrack(AUDIO_INPUT, 1)
+   // Default 2 channels for audio inputs.
+   : AudioTrack(AUDIO_INPUT, 2) //XXX force stereo because later switch to stereo is broken
       {
       for (int i = 0; i < MusECore::MAX_CHANNELS; ++i)
             jackPorts[i] = 0;

This way I can record my hard-synths and my stage piano now, stereo. Restriction: An input switched stereo --> mono --> stereo shows the same issue again - signal on left channel only forever.

Of course, this patch is not a solution, but it specifies the code area in which the error can be tracked.

**Comment by terminator356** [comment] 2020-05-23 16:47
Thanks for the check.
I did some preliminary testing. The problem is the actual mono/stereo switch.
I discovered that with an Audio Output, in its default stereo mode, the right channel
 connection works, until you switch from stereo to mono and then back to stereo.
Then it exhibits the same problem as Audio Input - the right connection refuses to work.
So the problem is definitely the actual switch.
I may have broken it recently, with some changes to the Jack port routines.
I'm just finishing up some other work, will get on this ASAP !

**Comment by terminator356** [comment] 2020-05-24 05:47
I broke it one month ago. Fixed in git master now. Thanks!

- Fix regression at 06.04.2020: Can't connect Jack ports to audio input/output tracks R chan.
Don't check out of bounds index in AudioInput/Output::registerPorts(). When it is called
 by Audio::msgSetChannels(), the new number of channels has not been set yet.

**Closed** 2020-05-26 06:38 UTC

**Comment by Gnlfz007** [comment] 2020-05-26 06:43
Whoa, the "close" button acts immediately, no comment, no question ... I'm used to JIRA @ work which is so over-precautious and sticky.

The issues resolved. Switching input or audio tracks back and forth between mono and stereo works as expected now. Thanks for this quick response.
