### ISSUE TITLE
Snap: Bar has to be re-selected if changing timesignature

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#874] opened 2020-10-19 09:13 UTC
Create a new project. Default time sig is 4/4.

Set Snap to Bar.

Change time sig to 6/8.

Create a MIDI track and create a bar on this MIDI track  -- it still thinks the time sig is 4/4.

Drag a copy one bar -- it still thinks the time sig is 4/4.

Set snap to Bar.

It works.

What a Bar is should possibly be recalculated when changing time sig.

Edit: This also seems to affect the End/Right marker and the looping.

**Comment by terminator356** [comment] 2020-10-19 15:01
I'll check later today. Might be my fault with the recent snap changes...

**Comment by terminator356** [comment] 2020-10-20 04:14
I think I am observing essentially the same thing.
I saw this before as I fixed the division/snapping (see my last log change), but I didn't get a chance to fix it:

1) Set 4/4 at time zero.
2) Draw a part on a track.
3) Set snap to bar.
4) Confirm dragging works, snaps to bar.
5) Set 6/8 at time zero.
6) Observe dragging the part to the right **does not seem** to snap to bar, instead snapping to
     where 4/4 bar lines **would have been**.
7) **But:** Observe that continuously dragging the part further actually cause it to snap **backwards**
    to the correct 6/8 lines. The part jumps forward and backward as you drag it.

I recall taking a look at the code responsible. I meant to make note of it but didn't.
I believe the code was the **existing snap code**, not my changes.
As I recall, and have just confirmed, a workaround is to **not use bar snap**. ie. use snap to 1/2 or 1/4 etc.
If I recall the code had trouble with bar snap (where there are no further division lines), I think I reasoned that
 the tick-to-BBT routines might be giving us the wrong Bar.

**Comment by StaffanMelin** [comment] 2020-10-20 07:09
Yes, iI observed #7 too when I examined this more closely.

But note that when I go from "Snap: Bar" to for example "Snap: 1/4" and back to "Snap: Bar", it begins to work. Seems like there is some recalculation happening when selecting "Snap: Bar"?

Anyway, the workaround is fine. Thanks for looking into this!

**Comment by spamatica** [comment] 2020-10-21 13:59
Observed #7 on a song I did now too. I'm pretty sure this behaviour is new.

**Comment by kybos** [comment] 2020-11-14 19:15
I experienced it too. It still worked in 3.1.1, just tested.

I had a brief look at the (new) snap code. I may be mistaken (it's quite complicated), but I have the impression that there is no real support for Bar snap at all. The existing Bar option is a fixed whole note in reality, so it only works with 4/4, 2/2, 8/8 etc. signatures (that amount to one whole note). For other signatures the grid subdivisions and the snapping are wrong, and the position cursor jumps around, because the mapping function between mouse position and the raster gets wrong input from the rasterizer.

**Comment by terminator356** [comment] 2020-11-15 15:14
Just to warn: I have identified the problem(s) and I am attempting to fix them today.
Thanks for the reports!

**Comment by terminator356** [comment] 2020-11-17 07:16
OK Try it now in git master or daily appimage.

No time to explain right now, will update change log later.

1) Arranger snap list gains a new row: 1/1
2) Editor snap boxes gain a new row: Bar
3) Regardless of snap setting, the rastering code limits all snap to a full bar.
ie. if signature is 2/16 and snap is on 4, 2, 1, or Bar, the actual snap is limited to a full bar.
This was not respected before and was causing the jumping around in **existing code** at SigList::raster() and similar functions.
The formula used there does not like when raster value > bar length.
Theoretically we **could** make snap work beyond a full bar, but no time right now, and it kind of doesn't
 make sense - an odd grid laid over a series of bars. The current code wants to reset the raster counter **at each bar**.
I can explain later...
4) Wave editor time-line and snap have been fixed. Position readouts also snap now. TODO: Still fix grid drawing...

Ideas for near future:
1) Hands up for including all three columns (but no more rows) in the Arranger snap list,
 because with triplet-based or dotted-based time signatures users may want to snap to a triplet or dotted.
2) The editors need a length snap box! The existing snap box would become the positional snap box.
Because our current **single** snap box governs both the position **and** length of drawn notes!
This does not seem good. Tedious to draw notes?

Cheers.
Tim.

**Comment by kybos** [comment] 2020-11-17 09:13
Thanks, the snap works perfectly now, AFAICS! Also for adding the new options!

>     3. Regardless of snap setting, the rastering code limits all snap to a full bar.
>        ie. if signature is 2/16 and snap is on 4, 2, 1, or Bar, the actual snap is limited to a full bar.
>        This was not respected before and was causing the jumping around in **existing code** at SigList::raster() and similar functions.
>        The formula used there does not like when raster value > bar length.

In my testcase it also jumped when raster value < bar length (in SigList::raster() etc.), as I tested with signatures like 5/4. But it's not relevant anymore, as it works in all cases now.

>     2. The editors need a length snap box! The existing snap box would become the positional snap box.
>        Because our current **single** snap box governs both the position **and** length of drawn notes!
>        This does not seem good. Tedious to draw notes?

Sounds interesting, would be nice to have. I never missed it, to be frank, but that has nothing to say, I am sure there are more advanced users than I am ;-).

I noticed the grid drawing in the Arranger is not yet correct when Snap=Bar and Signature e.g. 6/4. The subdivision after 4 beats shouldn't be there:

![image](https://user-images.githubusercontent.com/10009541/99369952-5b434f80-28bd-11eb-9caa-826372e9ddb3.png)

**Comment by StaffanMelin** [comment] 2020-11-17 09:40
Tried it with a waltz, everything works now.

Started a new project, default time sig 4/4.

Created a MIDI track and drew a part, 1 bar.

Changed the time sig to 6/8.

Nothing is redrawn or changed. Shouldn't the display reflect these changes?

![muse_snap](https://user-images.githubusercontent.com/33361311/99373086-4cf73280-28c1-11eb-996b-3bb08b2bf30d.png)

**Comment by kybos** [comment] 2020-11-17 09:47
Strange, it works for me (both with toolbar and transport window).
If you compiled yourself - are you using the new executable (muse4)?

**Comment by StaffanMelin** [comment] 2020-11-17 13:57
> If you compiled yourself - are you using the new executable (muse4)?

I used the AppImage (4 hours ago). Will download the source and compile...

**Comment by kybos** [comment] 2020-11-17 14:14
AppImage should be OK, it's rebuilt after each push. Did you try to reset the settings? Paths and other things changed because of the new version - I had lots of weird behaviour yesterday too, before I updated everything...

**Comment by StaffanMelin** [comment] 2020-11-17 14:36
Now it works!

I compiled from source AND removed the config folder.

Thanks -- looking great!

And I haven't seen the new mixer strip buttons -- thumbs up!

**Comment by terminator356** [comment] 2020-11-18 00:43
> I noticed the grid drawing in the Arranger is not yet correct when Snap=Bar and Signature e.g. 6/4. The subdivision after 4 beats shouldn't be there:

Yeah the only thing I could do was search for the terms "raster == 0" or "rast == 0" and correct them,
 as seen in SigList::raster() and similar, so I may have missed some places that still need correction.

One such place I found but still needs correction is in PartCanvas::drawCanvas() :
` ...`
`        if(rast == 0) // Special for arranger 'bar' snap.`
`        {`
` // This line looks suspicious, I know it must be wrong.`
` // It says that if the snap is on 'bar' then we use a raster`
` // value of one whole note - which is incorrect, it is **not** the same thing as a bar !  `
` // I think it explains what we are seeing. `
` // I could not fix it yet because I think possibly the whole drawTickRaster() needs rewriting `
` // to acknowledge bar snap. Here there is no given position to feed to SigList::raster() `
` // and do it correctly. `
`          rast = MusEGlobal::sigmap.ticks_beat(1);`
`        }`
`        drawTickRaster(p, mr, mrg, rast,`
` ...`

**Comment by terminator356** [comment] 2020-11-19 06:33
I think I see what to do. Hang in there, don't close this one just yet...

**Comment by kybos** [comment] 2021-01-13 15:21
Fixed by Tim.

**Closed by kybos** 2021-01-13 15:21 UTC
