### ISSUE TITLE
Feature Request: Auto-return

### ISSUE THREAD

**Issue by lrfinotti** [muse-sequencer/muse#664] opened 2019-10-01 18:53 UTC
I think it could be quite useful to have an *auto-return* toggle, which when activated would make the play-head return to where it started after hitting stop.  It is quite useful to test changes.

**Comment by davidhealey** [comment] 2019-10-19 00:21
Duplicate of #644

**Comment by spamatica** [comment] 2019-11-04 22:20
Implemented in head now

**Closed by spamatica** 2019-11-04 22:20 UTC
