### ISSUE TITLE
Unexpected behaviour in the piano roll when several keys at pressed the same time with a loaded sythn plugin.

### ISSUE THREAD

**Issue by dlzi** [muse-sequencer/muse#1008] opened 2021-05-22 10:32 UTC
It seems that any synth plugin like Vital, Surge and even the built-in one will trigger some unexpected behaviour in the piano roll once you press several keys at the same time. What happens is that the generated sound doesn't stop. 

Steps to reproduce the behaviour:
1. Install any synth plugin like Vital or Surge for example or use the built-in one.
2. Right click on track pane and choose Synth -> LV2|VST|MESS -> your synth
3. Right click on track pane and create a MIDI track
4. With your mouse, trigger several keys at the same time.

**Expected behavior**
The generated sound should stop once you stop pressing a key. 

**Desktop (please complete the following information):**
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.10.36-2-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-8565U CPU @ 1.80GHz
Memory: 15,5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

Muse 4 

*** Build info ***
LV2 support:		Enabled
DSSI support:		Enabled
Native VST support:	Enabled (using VESTIGE compatibility layer)

*** Runtime information ***
Running audio driver:	RtAudioDevice
RT audio driver:	LINUX_PULSE
Sample rate:		44100
Segment size:	512
Segment count:	2

*** Timer ***
Type:		AlsaTimer
Frequency:		300

*** Miscellaneous ***
debugMode:		false
midInputTrace:	false
midiOutputTrace:	false
unityWorkaround:	false
debugMsg:		false
heavyDebugMsg:	false
debugSync:		false
loadPlugins:		true
loadMESS:		true
loadVST:		true
loadNativeVST:	true
loadDSSI:		true
usePythonBridge:	false
useLASH:		true
loadLV2:		true
useAlsaWithJack:	false
noAutoStartJack:	false
populateMidiPortsOnStart:	true
realtimeScheduling:	true
midiRTPrioOverride:	true
realtimePriority:	40
midiSeqRunning:	true
automation:		true

**Comment by kybos** [comment] 2021-05-22 15:41
> * Right click on track pane and create a MIDI track
> 
> * With your mouse, trigger several keys at the same time.

Where/How do you trigger several keys at the same time?

**Comment by dlzi** [comment] 2021-05-22 20:21
With your mouse, click on a key in the piano roll and mouse over up and down the other keys.

**Comment by terminator356** [comment] 2021-05-22 22:57
Hello. I could not reproduce this.
Can you tell me, are multiple notes stuck or is it just one note as you move around?

I did observe one situation where a stuck note could occur:
If you **right-click** the mouse **before** releasing the left button, the note will be stuck.
That should be fixed. But it should not affect users during normal use at the moment, no-one should be noticing that.
What kind of mouse are you using - track pad or ball type or other?
Is it possible some kind of accessibility feature is enabled where no left-mouse-release messages are generated,
 or a right-click message is generated after a left-click? Try a different mouse?
Any stuck note should release when you move the mouse **outside** of the piano keyboard area. Does that happen?

Our piano keyboard uses a 'stuck notes' mechanism to ensure that notes are released.
Ironically, yesterday I just finished correcting some other parts in the app that use stuck notes.
So thank you for bringing this up, I missed examining the piano keyboard code !
So I checked the code and everything looks fine, no corrections seem to be required.

Thanks.

**Comment by dlzi** [comment] 2021-05-23 09:11
- Yeah... I couldn't find the word. A stuck note. That was my problem. :-)
- I'm using a "normal" three buttons mouse.
- Humm...I cannot reproduce the issue again. After I rebooted the system, things seems to be normal now. 

I'm sorry for this false alarm. Feel free to close the issue. 

Thanks.

**Comment by spamatica** [comment] 2021-05-23 14:11
Alright, no worries :)
Let me just add that if notes do get stuck (there are still ways this can happen), there is the Panic button on the toolbar which will send various reset commands (and note off) to all configured midi devices.

**Closed by spamatica** 2021-05-23 14:11 UTC
