### ISSUE TITLE
Routing doesn't work with sources/destinations contain utf-8 symbols

### ISSUE THREAD

**Issue by ChihHao-Su** [muse-sequencer/muse#1119] opened 2023-04-16 12:09 UTC
**Target version**
MusE 4.1 Flatpak

**Describe the bug**
- In the destinations and sources diagram (the upper part of the dialog), all non-latin charaters turn into `?`.
  ![螢幕快照 2023-04-16 19-48-29](https://user-images.githubusercontent.com/22293202/232308461-cdd5700d-5408-47e2-b19c-659a38a0b173.png)

- Click a row in the distinations and sources table (the lower part of the dialog), MusE cannot show the corresponding distinations and sources linkage on the destinations and sources diagram.
  ![螢幕快照 2023-04-16 19-55-19](https://user-images.githubusercontent.com/22293202/232308470-b4935689-5010-424e-9b74-68824092deb1.png)

**Expected behavior**
* Non-latin characters show normally.
* Linkage of destinations and sources contain utf-8 symbols works normally.

**Desktop (please complete the following information):**
 - OS: Fedora 37
 - Desktop: Gnome

**Comment by terminator356** [comment] 2023-04-17 00:01
Hello. My initial tests:
![Screenshot_20230416_194039](https://user-images.githubusercontent.com/5422362/232349804-8dcf4840-7c51-4328-82ce-97633abd8851.png)

The good news is that non-UTF8 characters seem to be working OK. Save and load are OK.
I was worried that it might be broken.

(Hm, the lines are supposed to be different colours. Broken drawing?)

In the screenshot, I do not have any Jack Audio terminals with non-UTF8 characters
 like your screenshot. So I could only test renaming a couple of tracks to non-UTF8 characters.
I must see if I can tell Jack to rename some ports to non-UTF8 characters so I can test that part.
Maybe the Jack Meta system will help.

Therefore I must suspect that there might be a bug in our specific code section(s)
 that work with Jack port names, such that by the time the router displays the names 
in the 'Jack' source/destination sections, they are mangled. 
Because so far **_some_** of the other router source/destination types seem OK.

In the screenshot, even though I am in an en-US locale, I am temporarily using 
 a French c locale _and_ application locale for testing some other locale bugs.
So this bug report comes at an interesting coincidental time.

**Comment by ChihHao-Su** [comment] 2023-04-17 00:33
My system locale is zh_TW.UTF-8, shouldn't the broken jack port name 
(shown in my screenshot) be UTF-8?

**Comment by terminator356** [comment] 2023-04-17 00:44
Sorry I was probably confusing terms.
Wide characters is probably what I should have said.
There is likely a bug with wide characters specifically in the router dialog's source/destination lists code.
Clearly they are working in the lower connection list but not the upper lists.

**Comment by terminator356** [comment] 2023-04-17 05:41
I did a test. I added some wide characters to the upstream routes Jack audio port names.
In other words, it is **_as if_** my audio device has Jack ports with wide character names, just like yours.
I could not reproduce the problem, as shown:
![Screenshot_20230417_012647](https://user-images.githubusercontent.com/5422362/232388618-044e3158-c7d5-4e12-8f6b-d8f92c74086d.png)

Can you do some more checks for me? I need to know if other routing items are working for you.
Please do what I did in my first screenshot: 
Create a Wave track and rename the track so it contains wide characters.
(I use the KCharSelect character selection utility which lets me paste wide characters into text.)
Maybe try creating a few more tracks just like that. Midi track, Group track etc.

Then, open the router and see what happens.
Are all the wide character names of those tracks displaying properly?

Thanks.

**Comment by ChihHao-Su** [comment] 2023-04-17 12:56
OK, I have created some track contain wide characters:
![圖片](https://user-images.githubusercontent.com/22293202/232489456-2f6006e2-2654-4874-8c23-8bbe1b4872f8.png)
In the router, these tracks look fine.
![圖片](https://user-images.githubusercontent.com/22293202/232489897-28f38037-7979-44c2-a666-b4d7db8b7f9a.png)
The jack ports contain wide characters cannot display properly.
![圖片](https://user-images.githubusercontent.com/22293202/232490177-4a2387f4-fdd4-45ef-822d-79bb89593b4c.png)

**Comment by ChihHao-Su** [comment] 2023-04-17 13:20
I tried the latest AppImage release (4.1), the problem still exits.

**Comment by ChihHao-Su** [comment] 2023-04-17 13:49
When I open the router, I found the console shows:
```
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:4695 jack_port_name()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:5048 jack_port_get_aliases()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:4695 jack_port_name()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:5048 jack_port_get_aliases()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:4695 jack_port_name()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:5048 jack_port_get_aliases()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:4695 jack_port_name()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:5048 jack_port_get_aliases()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:4695 jack_port_name()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:5048 jack_port_get_aliases()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:4695 jack_port_name()
'o != NULL' failed at ../pipewire-jack/src/pipewire-jack.c:5048 jack_port_get_aliases()
```
I don't know is that related to this issue.

**Comment by ChihHao-Su** [comment] 2023-04-18 00:45
> Are you able to build from github master source?

Sure, I can try building form source after I get off my work.

/ > //If I push a few debugging output lines into the code base just for 
you, are you able to test?/

I think yes, if I can//compile MusE successfully. I think we can try 
this first. If things get complicated and you need to debug on my 
machine, I can allow you to remote control my PC for a period of time./
/

**Comment by ChihHao-Su** [comment] 2023-04-18 11:20
Well, my system locale is zh_TW.UTF-8, shoudn't these jack terminals name with chinese characters (shown in my screenshot) be UTF-8?

於 2023年4月17日 上午8:01:25 [GMT+08:00]，Tim ***@***.***> 寫到：
>Hello. My initial tests:
>![Screenshot_20230416_194039](https://user-images.githubusercontent.com/5422362/232349804-8dcf4840-7c51-4328-82ce-97633abd8851.png)
>
>The good news is that non-UTF8 characters seem to be working OK. Save and load are OK.
>I was worried that it might be broken.
>
>(Hm, the lines are supposed to be different colours. Broken drawing?)
>
>In the screenshot, I do not have any Jack Audio terminals with non-UTF8 characters
> like your screenshot. So I could only test renaming a couple of tracks to non-UTF8 characters.
>I must see if I can tell Jack to rename some ports to non-UTF8 characters so I can test that part.
>Maybe the Jack Meta system will help.
>
>Therefore I must suspect that there might be a bug in our specific code section(s)
> that work with Jack port names, such that by the time the router displays the names 
>in the 'Jack' source/destination sections, they are mangled. 
>Because so far **_some_** of the other router source/destination types seem OK.
>
>In the screenshot, even though I am in an en-US locale, I am temporarily using 
> a French c locale _and_ application locale for testing some other locale bugs.
>So this bug report comes at an interesting coincidental time.
>
>

**Comment by ChihHao-Su** [comment] 2023-04-18 14:28
Hi, I have built MusE from source (master branch) sucessfully.

於 2023年4月18日 上午12:12:06 [GMT+08:00]，Tim ***@***.***> 寫到：

**Comment by terminator356** [comment] 2023-04-28 06:24
Hello @ChihHao-Su Sorry for the long delay. 

I have reproduced the problem. And I have found the trouble.
And I have just pushed a fix in github master.

Changed all QString::toLatin1()/tolocal8Bit() usages to QString::toUtf8() in the following files so far:
jack.cpp, jackmidi.cpp, route.cpp.
TODO: CHECK: Likely (many) more to do, EXCEPT some parts like xml, where we want SOME latin1 compatibility.

Try it and let me know if any more trouble.
I expect there may be more troubles. 
We have many places still using QString::toLatin1()
I am investigating...

Hope that helps with the issue so far. Good luck.

**Comment by ChihHao-Su** [comment] 2023-05-10 13:51
Hi,

It seems that things gets worse after I pulling the master branch. When I startup muse4, I got:
```
➜  /opt muse4                                    
User instrument directory does not exist. Creating it.
Config File </home/chihhao-su/.config/MusE/MusE/MusE-seq.cfg>
no locale <muse_zh_TW>/</usr/local/share/muse-4.1/locale>
LOCALE zh_TW
Config File </usr/local/share/muse-4.1/themes/Dark Flat.cfc>
open projectfile: 沒有此一檔案或目錄
Denormal protection enabled.
Select audio device from configuration : 0
User JackAudio backend - backend selected through configuration
Using Jack
Initializing Native VST support. Using VESTIGE compatibility implementation.
WARNING: Cannot lock memory:: 無法配置記憶體
MusE: JackAudioDevice::realtimePriority: JACK is not running realtime
WARNING: Cannot lock memory:: 無法配置記憶體
jack connect <pw-MusE:jack-midi-0_out> - <Midi-Bridge:Midi Through:(playback_0) Midi Through Port-0> failed with err:22
jack connect <Midi-Bridge:Midi Through:(capture_0) Midi Through Port-0> - <pw-MusE:jack-midi-0_in> failed with err:22
jack connect <pw-MusE:jack-midi-1_out> - <Midi-Bridge:CASIO USB-MIDI 2:(playback_0) CASIO USB-MIDI MIDI 1> failed with err:22
jack connect <Midi-Bridge:CASIO USB-MIDI 2:(capture_0) CASIO USB-MIDI MIDI 1> - <pw-MusE:jack-midi-1_in> failed with err:22
starting with template /usr/local/share/muse-4.1/templates/default.med
jack connect <pw-MusE:Out 1-0> - <內部音效 類比立體聲:playback_FL> failed with err:22
jack connect <pw-MusE:Out 1-1> - <內部音效 類比立體聲:playback_FR> failed with err:22
jack connect <pw-MusE:jack-midi-0_out> - <Midi-Bridge:Midi Through:(playback_0) Midi Through Port-0> failed with err:22
jack connect <Midi-Bridge:Midi Through:(capture_0) Midi Through Port-0> - <pw-MusE:jack-midi-0_in> failed with err:22
jack connect <pw-MusE:jack-midi-1_out> - <Midi-Bridge:CASIO USB-MIDI 2:(playback_0) CASIO USB-MIDI MIDI 1> failed with err:22
jack connect <Midi-Bridge:CASIO USB-MIDI 2:(capture_0) CASIO USB-MIDI MIDI 1> - <pw-MusE:jack-midi-1_in> failed with err:22
MusE: JackAudioDevice::realtimePriority: JACK is not running realtime
WARNING: Cannot lock memory:: 無法配置記憶體
```
There's a lot of "jack connect <xxxxx>-<yyyyyy> failed with err:22" which are abnormal, others are just fine.

And, I cannot connect ANYTHING in muse to jack ports in muse4. For example, I have:

![圖片](https://github.com/muse-sequencer/muse/assets/22293202/8b79d24b-f454-490c-891f-778500183765)

But the graph in qjackctl shows:

![圖片](https://github.com/muse-sequencer/muse/assets/22293202/7f835601-6234-40ee-a66d-f863bd6456df)

Now the only way to get output of muse form my device / get input in muse form my device is to connect them in qjackctl manually.

**Comment by terminator356** [comment] 2023-05-14 20:54
Hi @ChihHao-Su .
I have been studying your posted results for a few days now.
I am very puzzled about what's going on here.

I need to ask: **Do you recall**, about the text that was posted (the text with all the error 22),
 is this text the the actual output from the same session as the two pictures posted below the text?
Or is the text from a different session than the one from the two pictures?

I am asking because there is something strange about the text vs. pictures.
The text indicates PipeWire is altering MusE's Jack client name: 
It says "pw-MusE". (It is OK, it is allowed to do that).
For example the "<pw-MusE:Out 1-0>" etc.
**But** in the two pictures MusE's Jack client name is just "MusE".
This could not be possible, I think.
**Please clarify.**

About the textual jack connect errors:
===============================
We usually see error 17 (it is normal and means the connection already exists).
But we do not usually see error 22. Error 22 means "invalid argument". 
This means one or more of the three arguments passed to Jack's jack_connect() function is invalid.
They are: The client pointer, the source port name text, and the destination port name text.
But from the textual error output everything _seems_ OK.
For example the source client is "pw-MusE" and the source name is "jack-midi-1_out",  and the destination
 client is Midi-Bridge and the destination name is "CASIO USB-MIDI 2:(playback_0) CASIO USB-MIDI MIDI 1".

Both "jack-midi-1_out" and "CASIO USB-MIDI 2:(playback_0) CASIO USB-MIDI MIDI 1" do exist
on your QJackCtl graph, in the second picture.
However, our client name is just "MusE" in the second picture.
It does not match the text.

So I am puzzled by this.
**Can you verify** and maybe post some more pictures and console text?
Please also use the **-D command line option** for more debugging output.
**Also** if you could take a few pictures with MusE's router showing "Normal", "Alias1", and "Alias2",
 that would be good.

**And last**... what about the original issue, the utf8 characters? Is that working now?

Thanks for your help.

**Closed** 2023-08-08 13:42 UTC

**Comment by terminator356** [comment] 2023-08-08 20:52
Thank you.
I hope it works well for you.
Let us know if any more trouble.
