### ISSUE TITLE
Mastertrack listeditor undo handling behaves strange [sf#1094264]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#63] opened 2013-09-10 14:58 UTC
Submitted by lunar_shuttle on 2005-01-02 02:03:07

The undo handling for the mastertrack listeditor behaves 
strange (especially for time signature events). This probably 
has to do with tick-values changing after events are deleted or 
added etc + internal list handling. Applies to both HEAD and 
REL07.

**Comment by kybos** [comment] 2020-10-01 11:11
Confirmed.
The master list editing is generally quite buggy and even leads to crashes.

**Comment by kybos** [comment] 2021-01-31 14:14
I had fixed most of the editing bugs and crashes. I see no apparent problem with the undo, so closing this.
This editor seems to be hardly used anyway, as nobody complained about the many existing problems.

**Closed by kybos** 2021-01-31 14:14 UTC
Labels: bug, import
